### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by davidhesselbom** [gustafsson/freq#14]
The following files include a non-existing `LICENSE` file: 
- `filters.pro`
- `heightmap.pro`
- `justmisc.pro`
- `signal.pro`
- `tfr.pro`
- `tfrheightmap.pro`

How is this fixed &mdash; by adding the missing files, or by removing the includes?

If the latter, be aware that `gpumisc.pro` and `backtrace.pro` also include such a file, but in those cases, one that exists. Should the files and the includes be removed?

**Comment by gustafsson** [comment]
By removing the references in each .pro file. Backtrace and gpumisc works
as a projects by themselves, and have been used as such. The others, not so
much.
tis 22 sep 2015 kl. 23:33 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Okay, I'll do that, then.
